<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Copyright>Copyright © Nop Solutions, Ltd</Copyright>
    <Company>Nop Solutions, Ltd</Company>
    <Authors>Nop Solutions, Ltd, Fuad Hasan</Authors>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl>https://www.nopcommerce.com/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nopSolutions/nopCommerce</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <OutputPath>..\..\Presentation\Nop.Web\Plugins\Misc.BambooCard.Core</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <!--Set this parameter to true to get the dlls copied from the NuGet cache to the output of your project.
    You need to set this parameter to true if your plugin has a nuget package 
    to ensure that the dlls copied from the NuGet cache to the output of your project-->
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Admin\Components\**" />
    <Compile Remove="Areas\Admin\Events\**" />
    <Compile Remove="Areas\Admin\Extensions\**" />
    <Compile Remove="Areas\Admin\Helpers\**" />
    <Compile Remove="Areas\Admin\Infrastructure\**" />
    <Compile Remove="Areas\Admin\Themes\**" />
    <Compile Remove="Components\**" />
    <Compile Remove="Controllers\**" />
    <Compile Remove="Data\**" />
    <Compile Remove="Domains\**" />
    <Compile Remove="Dtos\**" />
    <Compile Remove="Events\**" />
    <Compile Remove="Extensions\**" />
    <Compile Remove="Factories\**" />
    <Compile Remove="Helpers\**" />
    <Compile Remove="Models\**" />
    <Compile Remove="Themes\**" />
    <Compile Remove="Views\**" />
    <EmbeddedResource Remove="Areas\Admin\Components\**" />
    <EmbeddedResource Remove="Areas\Admin\Events\**" />
    <EmbeddedResource Remove="Areas\Admin\Extensions\**" />
    <EmbeddedResource Remove="Areas\Admin\Helpers\**" />
    <EmbeddedResource Remove="Areas\Admin\Infrastructure\**" />
    <EmbeddedResource Remove="Areas\Admin\Themes\**" />
    <EmbeddedResource Remove="Components\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Domains\**" />
    <EmbeddedResource Remove="Dtos\**" />
    <EmbeddedResource Remove="Events\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Factories\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Themes\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="Areas\Admin\Components\**" />
    <None Remove="Areas\Admin\Events\**" />
    <None Remove="Areas\Admin\Extensions\**" />
    <None Remove="Areas\Admin\Helpers\**" />
    <None Remove="Areas\Admin\Infrastructure\**" />
    <None Remove="Areas\Admin\Themes\**" />
    <None Remove="Components\**" />
    <None Remove="Controllers\**" />
    <None Remove="Data\**" />
    <None Remove="Domains\**" />
    <None Remove="Dtos\**" />
    <None Remove="Events\**" />
    <None Remove="Extensions\**" />
    <None Remove="Factories\**" />
    <None Remove="Helpers\**" />
    <None Remove="Models\**" />
    <None Remove="Themes\**" />
    <None Remove="Views\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Areas\Admin\Views\BambooProductAttribute\List.cshtml" />
    <None Remove="Areas\Admin\Views\_ViewImports.cshtml" />
    <None Remove="Areas\Admin\Views\_ViewStart.cshtml" />
    <None Remove="logo.jpeg" />
    <None Remove="logo.png" />
    <None Remove="plugin.json" />
  </ItemGroup>
  
  <ItemGroup>
    <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="Areas\Admin\Views\BambooProductAttribute\List.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Areas\Admin\Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Areas\Admin\Views\_ViewStart.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Infrastructure\Middlewares\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Nop.Core\Nop.Core.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Data\Nop.Data.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Services\Nop.Services.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\NopStation.Plugin.Misc.Core\NopStation.Plugin.Misc.Core.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NopStation.Plugin.Misc.Actions">
      <HintPath>..\NopStation.Plugin.Misc.Core\NopStation.Plugin.Misc.Actions.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  
  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />

    <!-- Delete extra folders and files from plugin output directory -->
    <RemoveDir Directories="$(OutDir)\refs;$(OutDir)\ref;$(OutDir)\runtimes" />
    <Delete Files="$(OutDir)\$(AssemblyName).deps.json;$(OutDir)\$(AssemblyName).pdb;$(OutDir)\$(AssemblyName).staticwebassets.runtime.json" />
  </Target>

</Project>
