<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>NopStation.Plugin.Misc.AdminApi</AssemblyName>
    <RootNamespace>NopStation.Plugin.Misc.AdminApi</RootNamespace>
    <OutputPath>..\..\Presentation\Nop.Web\Plugins\NopStation.Plugin.Misc.AdminApi</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <Version>4.70.1.2</Version>
    <Authors>Nop-Station Team</Authors>
    <Company>Nop-Station</Company>
    <Product>Nop-Station Admin Api</Product>
    <AssemblyVersion>4.70.1.2</AssemblyVersion>
    <FileVersion>4.70.1.2</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Description>This plugin enables api for nopCommerce admin.</Description>
    <Copyright>Nop-Station Team</Copyright>
    <PackageTags>NopStation,AdminApi,NopCommerce,Plugin</PackageTags>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Areas\Admin\Controllers\Api\OrderController.cs" />
    <Compile Remove="Areas\Admin\Controllers\Api\RoxyFilemanController.cs" />
    <Compile Remove="Extensions\AttributeParserHelper.cs" />
    <Compile Remove="Extensions\HelperExtension.cs" />
    <Compile Remove="Extensions\MappingExtensions.cs" />
    <Compile Remove="Extensions\TransactMode.cs" />
    <Compile Remove="Extensions\WebApiPermissionProvider.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Areas\Admin\Views\AdminApi\Configure.cshtml" />
    <None Remove="Areas\Admin\Views\AdminApi\_Configure.AppSettings.cshtml" />
    <None Remove="Areas\Admin\Views\AdminApi\_Configure.Security.cshtml" />
    <None Remove="Areas\Admin\Views\_ViewImports.cshtml" />
    <None Remove="Areas\Admin\Views\_ViewStart.cshtml" />
    <None Remove="sitemap.config" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="Areas\Admin\Views\AdminApi\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Areas\Admin\Views\AdminApi\_Configure.AppSettings.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Areas\Admin\Views\AdminApi\_Configure.Security.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Areas\Admin\Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Areas\Admin\Views\_ViewStart.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="sitemap.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NopStation.Plugin.Misc.Actions">
      <HintPath>..\NopStation.Plugin.Misc.Core\NopStation.Plugin.Misc.Actions.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Nop.Core\Nop.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Data\Nop.Data.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Services\Nop.Services.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\NopStation.Plugin.Misc.Core\NopStation.Plugin.Misc.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="JWT">
      <HintPath>dll\JWT.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="loginStringResources.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>

  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />

    <!-- Delete extra folders and files from plugin output directory -->
    <RemoveDir Directories="$(OutDir)\refs;$(OutDir)\ref" />
    <Delete Files="$(OutDir)\$(AssemblyName).deps.json;$(OutDir)\$(AssemblyName).pdb" />
  </Target>

</Project>
